package prototype1_MinGyu;
import javax.swing.*;

public class GameViewAndControl extends javax.swing.JDialog {

    
    private int cnt = 0;
    private int rowcnt = 0;
    private int colcnt = 0;
	private char[] q = new char[]{' ',' ',' ',' ',' ',' ',' ',' '};
   private GameViewAndControl()
	{
		
	}
	
	private static  GameViewAndControl dialog = new GameViewAndControl(new javax.swing.JFrame(), true);
	public static GameViewAndControl getInstance(){
		return dialog;
	}
    public GameViewAndControl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInitComponents();
    }
    
    /* 
    * This method is called from within the constructor to initialize the form.
    */
    private void myInitComponents(){
        uiPlayButton = uiPlay;
        uiStopButton = uiStop;
     
        uiInstructionButtons[0] = uiBoxButton;
        uiInstructionButtons[1] = uiPutButton;
        uiInstructionButtons[2] = uiDeleteButton;
        uiInstructionButtons[3] = uiStarButton;
        
        uiInstructionQueue[0] = jLabel8;
        uiInstructionQueue[1] = jLabel7;
        uiInstructionQueue[2] = jLabel6;
        uiInstructionQueue[3] = jLabel5;
        uiInstructionQueue[4] = jLabel4;
        uiInstructionQueue[5] = jLabel3;
        uiInstructionQueue[6] = jLabel2;
        uiInstructionQueue[7] = jLabel1;
        
        uiUserBoard = jTable1;
        uiAnswerBoard = jTable2;
        uiInstructionButtons[0].setText("■");
        uiInstructionButtons[1].setText("→");
        for(int i=0;i<8;i++) uiInstructionQueue[i].setText(" ");
        
        uiJudgeText = jTextPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uiBoxButton = new javax.swing.JButton();
        uiPutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        uiPlay = new javax.swing.JButton();
        uiStop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uiDeleteButton = new javax.swing.JButton();
        uiStarButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        uiJudgeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        uiBoxButton.setText("■");
        uiBoxButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uiBoxButtonMouseClicked(evt);
            }
        });
        uiBoxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiBoxButtonActionPerformed(evt);
            }
        });
        uiBoxButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                uiBoxButtonKeyPressed(evt);
            }
        });

        uiPutButton.setText("→");
        uiPutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uiPutButtonMouseClicked(evt);
            }
        });
        uiPutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiPutButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        uiPlay.setText("▶");
        uiPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uiPlayMouseClicked(evt);
            }
        });
        uiPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiPlayActionPerformed(evt);
            }
        });

        uiStop.setText("■");
        uiStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiStopActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        uiDeleteButton.setText("DEL");
        uiDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uiDeleteButtonMouseClicked(evt);
            }
        });
        uiDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiDeleteButtonActionPerformed(evt);
            }
        });

        uiStarButton.setText("★");
        uiStarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uiStarButtonMouseClicked(evt);
            }
        });
        uiStarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiStarButtonActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jTextPane1);

        uiJudgeButton.setText("Judge");
        uiJudgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiJudgeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(uiBoxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiPutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiDeleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uiStarButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uiPlay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(uiStop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiJudgeButton)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiStop)
                    .addComponent(uiPlay)
                    .addComponent(uiJudgeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiBoxButton)
                    .addComponent(uiPutButton)
                    .addComponent(uiDeleteButton)
                    .addComponent(uiStarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uiDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiDeleteButtonActionPerformed

    private void uiBoxButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiBoxButtonMouseClicked
        // TODO add your handling code here:
         if(MinQueue.getInstance().getIndex()==8)
    		return;
        MinQueue.getInstance().inputQueue("■");
        uiInstructionQueue[7-(MinQueue.getInstance().getIndex()-1)].setText(""+MinQueue.getInstance().getQueue()[MinQueue.getInstance().getIndex()-1]);
    }//GEN-LAST:event_uiBoxButtonMouseClicked

    private void uiPutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiPutButtonMouseClicked
        // TODO add your handling code here:
       if(MinQueue.getInstance().getIndex()==8)
    		return;
        MinQueue.getInstance().inputQueue("→");
        uiInstructionQueue[7-(MinQueue.getInstance().getIndex()-1)].setText(""+MinQueue.getInstance().getQueue()[MinQueue.getInstance().getIndex()-1]);
    }//GEN-LAST:event_uiPutButtonMouseClicked

    private void uiDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiDeleteButtonMouseClicked
        if(MinQueue.getInstance().getIndex()==0)
            return;
        MinQueue.getInstance().deleteQueue();
        uiInstructionQueue[7-(MinQueue.getInstance().getIndex())].setText(""+MinQueue.getInstance().getQueue()[MinQueue.getInstance().getIndex()]);
    }//GEN-LAST:event_uiDeleteButtonMouseClicked

    private void uiPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiPlayActionPerformed
       
        for(int i=0; i<MinQueue.getInstance().getIndex(); i++)
        {
            if(rowcnt >= 8)
                return;
            if(colcnt >= 4)
                return;
            if(MinQueue.getInstance().getQueue()[i].equals("→"))
            {
                colcnt++;
                rowcnt = 0;
            }
            else
            {
                jTable1.setValueAt(MinQueue.getInstance().getQueue()[i], 7-rowcnt, colcnt);
                rowcnt++;
            }
            
        }
    }//GEN-LAST:event_uiPlayActionPerformed

    private void uiStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiStopActionPerformed
        
        for(int i=0; i<8; i++)
        {
            for(int j=0; j<4; j++)
            {
                jTable1.setValueAt(" ",i, j);
            }
        }
      
    }//GEN-LAST:event_uiStopActionPerformed

    private void uiBoxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiBoxButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiBoxButtonActionPerformed

    private void uiPutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiPutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiPutButtonActionPerformed

    private void uiPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiPlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_uiPlayMouseClicked

    private void uiBoxButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uiBoxButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiBoxButtonKeyPressed

    private void uiStarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiStarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiStarButtonActionPerformed

    private void uiStarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uiStarButtonMouseClicked
        // TODO add your handling code here:
         if(MinQueue.getInstance().getIndex()==8)
    		return;
        MinQueue.getInstance().inputQueue("★");
        uiInstructionQueue[7-(MinQueue.getInstance().getIndex()-1)].setText(""+MinQueue.getInstance().getQueue()[MinQueue.getInstance().getIndex()-1]);
    }//GEN-LAST:event_uiStarButtonMouseClicked

    private void uiJudgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiJudgeButtonActionPerformed
        // TODO add your handling code here:
        Judge.mark();
    }//GEN-LAST:event_uiJudgeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public javax.swing.JTextPane getJudge(){
        return uiJudgeText;
    }
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameViewAndControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameViewAndControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameViewAndControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameViewAndControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton uiBoxButton;
    private javax.swing.JButton uiDeleteButton;
    private javax.swing.JButton uiJudgeButton;
    private javax.swing.JButton uiPlay;
    private javax.swing.JButton uiPutButton;
    private javax.swing.JButton uiStarButton;
    private javax.swing.JButton uiStop;
    // End of variables declaration//GEN-END:variables

    // Vaiables declaration - modifiable
    private javax.swing.JButton[] uiInstructionButtons = new javax.swing.JButton[8];
    private javax.swing.JLabel[] uiInstructionQueue = new javax.swing.JLabel[8];
    private javax.swing.JButton uiPlayButton;
    private javax.swing.JButton uiStopButton;
    private javax.swing.JTable uiUserBoard;
    private javax.swing.JTable uiAnswerBoard;
    private javax.swing.JTextPane uiJudgeText;
}
